### ISSUE TITLE
plsmod Dependency

### ISSUE THREAD

**Issue by viv-analytics** [selcukorkmaz/fastml#7]
Hi @selcukorkmaz

There is an issue while installing {fastml 0.3.0} from CRAN due to its dependency to plsmod and in particlar {mixOmics} which is only available through Bioconductor. https://bioconductor.org/packages/release/bioc/html/mixOmics.html

Q: Is plsmod a critical dependency of {fastml}? Can it be substituted to stay consistent within CRAN?

Best wishes

**Comment by selcukorkmaz** [comment]
The issue has been resolved in version 0.4.0.

**Comment by selcukorkmaz** [comment]
The issue has been resolved in version 0.4.0.

**Comment by viv-analytics** [comment]
![Image](https://github.com/user-attachments/assets/08cfc2d0-975f-4ef3-ba45-45f5d0fddbbc)

**Comment by jc-usda** [comment]
I think this is still an issue. installed 0.5.0 from CRAN today, and I got 
`Warning in install.packages :
  dependency ‘mixOmics’ is not available` 

I was still able to install `fastml`. 

When I run `library(fastml)`, I get an error 

``` r
library(fastml)
#> Warning: package 'fastml' was built under R version 4.4.3
#> Error: package or namespace load failed for 'fastml' in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
#>  there is no package called 'mixOmics'
```

<sup>Created on 2025-03-27 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>
